services:
  web:
    build: .
    command: sh -c "bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  test_db_migrate:
    build: .
    command: bundle exec rake db:migrate
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=test
    entrypoint: ["sh", "-c", "bundle exec rake db:migrate"]
    profiles:
      - test
  test:
    build: .
    command: bundle exec rspec spec
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=test
    entrypoint: ["sh", "-c", "bundle exec rspec spec"]
    profiles:
      - test